### ISSUE TITLE
package.json: exports problem

### ISSUE THREAD

**Issue by Disti4ct** [pedrouid/iso-random#1]
Hi, we got issue in our project because of [this commit](https://github.com/pedrouid/iso-random/commit/f9d962d8dbc7c2a95d1b7308b37db9581dd55a2a) and the addition of exports.
The issue is solved when I make a direct path to the file as seen in the screenshot.

![116966327-b46b3800-acd1-11eb-9216-07b077f14a16](https://user-images.githubusercontent.com/61930014/116979292-6da61f80-ac8a-11eb-8245-21ecef87eb6f.png)

Seems that this problem with webpack version (not sure).
Our version **"webpack": "^ 5.33.2"**

**Comment by pedrouid** [comment]
Thanks for reporting it @NotEternal 👍 I've published 1.2.1 with the proposed fix. Can you confirm that is now fixed?

**Comment by Disti4ct** [comment]
Thanks. Seems the problem resolved )
